# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16405c3a971184cd01d9369e295cc3e5f7b56ded5661b05401cf5eebdee2bdc2c3683dc878f55b327205d136da8c3bc6419c98ac382eed8d941d2989e39f1607

test:
  secret_key_base: 0ad8bc0f443204aec06465c5fa3aeb090991de1427ae0839744bea50e4c337fc1621e808c1f3169073fe12e2eb3ffa05a0a2820783b0a6d41696ce01e69a7dc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
